# Path to the template directories to load the body/textfiles
export TEMPLATE_PATH=./templates
export CONFIG_PATH=./config
export LOG_PATH=./logs
export PAYLOAD_PATH=../test/payload_files

# helo value
export HELO_NAME=localhost

# The mailserver to test
export MAILSERVER_NAME=mail.example.com

# The authentication user and password
export SENDER_AUTH_USER=test1@example.com
export SENDER_AUTH_PASSWORD=TestPassword

# Sender addresses for the different tests
export SENDER_ADDRESS_MAIN=test1@example.com
export SENDER_ADDRESS_ALIAS=test2@example.com
export SENDER_ADDRESS_MAIN_TAG=test1+extension@example.com
export SENDER_ADDRESS_ALIAS_TAG=test2+tag02@example.com

# Sender address: testing to send in behave of a different user (not allowed)
export SENDER_ADDRESS_DENIED=test3@example.com

# Sender address: testing to forge sender (mismatch envelope/data-from)
export SENDER_ADDRESS_FORGED=forged@example.com
export SENDER_ADDRESS_FORGED2=forged@example.net

# Recipient address for outbound emails
export RECIPIENT_ADDRESS=test@example.com

# External sender address
export SENDER_MAILLINGLIST=maillinglist@example.net
export SENDER_MAILLINGLIST_ORIGIN=sender@example.org
